name: Deploy St. Phillips API

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        id: checkout
        name: Get Repo
      - uses: actions/setup-node@v3
        id: node-setup
        name: Set Up Node 16.x
        with:
          node-version: 16
      - run: npm ci
        id: clean-install
        name: Install Node Packages
      - run: npm run build
        id: compile-api
        name: Compile API
      - id: gcp-auth
        name: Fetch GCP Authorization
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SA }}
      - id: deploy
        name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: spmbc
          env_vars: |-
            AUTH0_ISSUER=${{ secrets.AUTH0_ISSUER }}
            CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}
            NODE_ENV=production
            AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
            PORT=8080
            MONGO_USER=${{ secrets.MONGO_USER }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
